import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import confetti from 'canvas-confetti';
import Calendar from 'react-calendar';
import 'react-calendar/dist/Calendar.css';
import { BarChart3, CalendarDays, Check, ChevronRight, CircleHelp, CircleUserRound, Clock3, Flame, LayoutDashboard, ListTodo, LogOut, Menu, Moon, NotebookPen, Pencil, PieChart, Plus, Quote, Save, Search, Sparkles, Sun, TimerReset, Trash2, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import toast from 'react-hot-toast';
import { useAuth } from './context/AuthContext';
import { useTheme } from './context/ThemeContext';
import { api } from './services/api';
import { useCollection } from './hooks/useCollection';
import { Brand, EmptyState } from './components/ui';
import PublicSite from './pages/site/PublicSite';
import { navigate, useRoute } from './router';
import ScheduleView from './pages/ScheduleView';
import BudgetView from './pages/BudgetView';
import ExamView from './pages/ExamView';
import PlannerView from './pages/PlannerView';
import ProfileView from './pages/ProfileView';
import { dateKey, money, percentOf, todayKey } from './utils';

const subjects = ['All', 'Programming', 'Database', 'Mathematics', 'Networking', 'Web Development', 'English', 'Others'];
const quotes = ['Small progress is still progress.', 'Your future self is cheering for today.', 'Focus on the next useful step.', 'Consistency turns effort into results.'];
const colors = ['#ef8354', '#2b7a78', '#f4b942', '#7b61ff', '#ed6a5a', '#6c8ead'];
const blankTask = { title: '', subject: 'Programming', priority: 'Medium', dueDate: '' };
const nextMotivation = (current) => quotes.find((quote) => quote !== current) || current;

function App() {
  const { user, loading } = useAuth(); const path = useRoute();
  useEffect(() => { if (user && path !== '/') navigate('/', { replace: true }); }, [user, path]);
  useEffect(() => { if (user) document.title = 'StudyFlow'; }, [user]);
  if (loading) return <div className="loading-screen"><div className="spinner" /></div>;
  if (user) return <EnhancedDashboard />;
  if (path === '/login' || path === '/register') return <AuthPage key={path} initialMode={path === '/register' ? 'register' : 'login'} onBack={() => navigate('/')} />;
  return <PublicSite path={path} />;
}


function AuthPage({ initialMode = 'login', onBack }) {
  const { login, register } = useAuth(); const [mode, setMode] = useState(initialMode); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); try { if (mode === 'login') await login({ email: form.email, password: form.password }); else await register(form); toast.success(mode === 'login' ? 'Welcome back' : 'Account created'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to continue'); } finally { setBusy(false); } }
  return <main className="auth-page"><div className="auth-art"><button className="auth-back" onClick={onBack}><ChevronRight size={15} /> Back to home</button><Brand /><div className="art-copy"><p className="eyebrow">YOUR STUDY, IN RHYTHM</p><h1>Make space for your best work.</h1><p>Plan deliberately, focus deeply, and see your momentum build one session at a time.</p></div><div className="art-orbit"><div className="orbit-card"><Flame size={18} color="#ef8354" /><strong>7 day streak</strong><span>Keep showing up</span></div></div></div><section className="auth-card"><div className="mobile-brand"><Brand /></div><div className="auth-heading"><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'START FRESH'}</p><h2>{mode === 'login' ? 'Sign in to your flow' : 'Create your study space'}</h2><p>{mode === 'login' ? 'Your next focused session is waiting.' : 'A calmer way to manage your course load.'}</p></div><form onSubmit={submit}>{mode === 'register' && <label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Alex Morgan" /></label>}<label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@university.edu" /></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters" /></label><button className="primary-button full" disabled={busy}>{busy ? 'Opening your space...' : mode === 'login' ? 'Enter StudyFlow' : 'Create account'}<ChevronRight size={17} /></button></form><button className="switch-auth" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New to StudyFlow? Create an account' : 'Already have an account? Sign in'}</button></section></main>;
}

function EnhancedDashboard() {
  const { user, logout, updateProfile } = useAuth(); const { dark, toggleTheme } = useTheme();
  const schedules = useCollection('/schedules', 'schedule'); const transactions = useCollection('/transactions', 'transactions'); const attempts = useCollection('/quiz-attempts', 'quiz progress');
  const [view, setView] = useState('overview'); const [tasks, setTasks] = useState([]); const [subject, setSubject] = useState('All'); const [modal, setModal] = useState(null); const [editing, setEditing] = useState(null); const [mobileOpen, setMobileOpen] = useState(false); const [weekly, setWeekly] = useState([]); const [badges, setBadges] = useState([]); const [quote, setQuote] = useState(() => quotes[Math.floor(Math.random() * quotes.length)]);
  const load = async () => { try { const [taskResponse, weeklyResponse, badgeResponse] = await Promise.all([api.get('/tasks'), api.get('/study-sessions/weekly'), api.get('/badges')]); setTasks(taskResponse.data.tasks); setWeekly(weeklyResponse.data.days); setBadges(badgeResponse.data.badges); } catch { toast.error('Could not load your study space'); } };
  useEffect(() => { load(); }, []);
  const completed = tasks.filter((task) => task.isCompleted).length; const remaining = tasks.length - completed; const percent = tasks.length ? Math.round(completed / tasks.length * 100) : 0; const filtered = subject === 'All' ? tasks : tasks.filter((task) => task.subject === subject);
  const month = todayKey().slice(0, 7); const balance = transactions.items.filter((item) => dateKey(item.date).startsWith(month)).reduce((sum, item) => sum + (item.type === 'Income' ? item.amount : -item.amount), 0);
  const quizTotal = attempts.items.reduce((sum, item) => sum + item.total, 0); const quizAverage = percentOf(attempts.items.reduce((sum, item) => sum + item.correct, 0), quizTotal); const classesToday = schedules.items.filter((item) => dateKey(item.date) === todayKey()).length;
  const stats = { tasksDone: completed, tasksTotal: tasks.length, classes: schedules.items.length, balance, quizzes: attempts.items.length, quizAverage, focusMinutes: weekly.reduce((sum, day) => sum + day.minutes, 0) };
  const tiles = [
    { id: 'schedule', label: 'Schedule', icon: CalendarDays, tint: '#2563eb', value: schedules.items.length, note: classesToday ? `${classesToday} today` : 'classes planned' },
    { id: 'budget', label: 'Budget', icon: PieChart, tint: '#059669', value: money(balance), note: 'balance this month' },
    { id: 'exam', label: 'Exam Q&A', icon: CircleHelp, tint: '#7c3aed', value: attempts.items.length ? `${quizAverage}%` : 'Start', note: attempts.items.length ? 'average quiz score' : 'take your first quiz' },
    { id: 'planner', label: 'Planner', icon: NotebookPen, tint: '#f97316', value: remaining, note: 'pending tasks' }
  ];
  async function saveTask(task) { try { const response = editing ? await api.put(`/tasks/${editing._id}`, task) : await api.post('/tasks', task); setTasks(editing ? tasks.map((item) => item._id === editing._id ? response.data.task : item) : [response.data.task, ...tasks]); setModal(null); setEditing(null); toast.success(editing ? 'Task updated' : 'Task added'); } catch (error) { toast.error(error.response?.data?.message || 'Could not save task'); } }
  async function toggle(task) { try { const response = await api.patch(`/tasks/${task._id}/toggle`); const nextTasks = tasks.map((item) => item._id === task._id ? response.data.task : item); setTasks(nextTasks); if (response.data.task.isCompleted && nextTasks.every((item) => item.isCompleted)) confetti({ particleCount: 80, spread: 65, origin: { y: .7 } }); toast.success(response.data.task.isCompleted ? 'Task complete' : 'Task reopened'); } catch { toast.error('Could not update task'); } }
  async function remove(task) { if (!window.confirm(`Delete “${task.title}”?`)) return; await api.delete(`/tasks/${task._id}`); setTasks(tasks.filter((item) => item._id !== task._id)); toast.success('Task deleted'); }
  const go = (nextView) => { setView(nextView); setMobileOpen(false); };
  const newQuote = () => setQuote((current) => nextMotivation(current));
  const nav = [
    { id: 'overview', label: 'Overview', icon: LayoutDashboard, color: '#6366f1' }, { id: 'tasks', label: 'My tasks', icon: ListTodo, color: '#ef8354' }, { id: 'calendar', label: 'Calendar', icon: CalendarDays, color: '#0891b2' }, { id: 'timer', label: 'Focus timer', icon: Clock3, color: '#ca8a04' },
    { id: 'schedule', label: 'Schedule', icon: CalendarDays, color: '#2563eb' }, { id: 'budget', label: 'Budget', icon: PieChart, color: '#059669' }, { id: 'exam', label: 'Exam Q&A', icon: CircleHelp, color: '#7c3aed' }, { id: 'planner', label: 'Planner', icon: NotebookPen, color: '#f97316' },
    { id: 'profile', label: 'Profile', icon: CircleUserRound, color: '#db2777' }
  ];
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><Brand /><nav>{nav.map(({ id, label, icon: Icon, color }) => <button className={view === id ? 'active' : ''} key={id} onClick={() => go(id)}><span className="nav-ico" style={{ '--tint': color }}><Icon size={16} /></span> {label}{id === 'tasks' && <span className="nav-count">{tasks.filter((task) => !task.isCompleted).length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="mini-profile"><div className="avatar">{user.name[0]}</div><div><strong>{user.name}</strong><span>Student account</span></div></div><button onClick={logout} className="logout-button"><LogOut size={17} /> Log out</button></div></aside><div className="main-area"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(!mobileOpen)}><Menu size={20} /></button><div><p className="topbar-kicker">{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p><h2>{view === 'overview' ? `Good morning, ${user.name.split(' ')[0]}.` : nav.find((item) => item.id === view)?.label}</h2></div><div className="top-actions"><button className="icon-button" onClick={toggleTheme}>{dark ? <Sun size={19} /> : <Moon size={19} />}</button><div className="top-avatar">{user.name[0]}</div></div></header><main className="content">{view === 'overview' && <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><Overview tasks={tasks} completed={completed} percent={percent} quote={quote} onNewQuote={newQuote} onAdd={() => { setEditing(null); setModal({}); }} onNavigate={go} /><WeeklyPanel weekly={weekly} /><QuickTiles tiles={tiles} onNavigate={go} /></motion.div>}{view === 'tasks' && <TasksView tasks={filtered} subject={subject} setSubject={setSubject} onAdd={() => { setEditing(null); setModal({}); }} onToggle={toggle} onEdit={(task) => { setEditing(task); setModal({}); }} onDelete={remove} />}{view === 'calendar' && <CalendarView tasks={tasks} />}{view === 'schedule' && <ScheduleView schedules={schedules} />}{view === 'budget' && <BudgetView transactions={transactions} user={user} updateProfile={updateProfile} />}{view === 'exam' && <ExamView attempts={attempts} />}{view === 'planner' && <PlannerView tasks={tasks} setTasks={setTasks} onToggle={toggle} onDelete={remove} />}{view === 'timer' && <TrackedTimer onSession={load} />}{view === 'profile' && <ProfileView user={user} badges={badges} stats={stats} onNavigate={go} updateProfile={updateProfile} />}</main></div>{modal && <TaskModal initial={editing || blankTask} onClose={() => { setModal(null); setEditing(null); }} onSave={saveTask} />}</div>;
}

function WeeklyPanel({ weekly }) { return <section className="panel weekly-panel"><div className="panel-heading"><div><p className="eyebrow">STUDY TIME</p><h3>Focused minutes this week</h3></div><BarChart3 size={20} color="#ef8354" /></div>{weekly.length ? <ResponsiveContainer width="100%" height={180}><BarChart data={weekly} barSize={26}><CartesianGrid vertical={false} stroke="#e7e4df" /><XAxis dataKey="label" axisLine={false} tickLine={false} fontSize={11} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} fontSize={11} /><Tooltip /><Bar dataKey="minutes" fill="#ef8354" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer> : <EmptyState compact text="Complete a focus session to start tracking." />}</section>; }
function CalendarView({ tasks }) { const [date, setDate] = useState(new Date()); const dayTasks = tasks.filter((task) => task.dueDate && new Date(task.dueDate).toDateString() === date.toDateString()); return <div className="calendar-page"><div className="page-title-row"><div><p className="eyebrow">PLAN YOUR WEEK</p><h1>Study calendar.</h1><p className="muted">See every deadline in one calm view.</p></div></div><div className="calendar-layout"><section className="panel calendar-panel"><Calendar onChange={setDate} value={date} tileContent={({ date: tileDate }) => tasks.some((task) => task.dueDate && new Date(task.dueDate).toDateString() === tileDate.toDateString()) ? <span className="calendar-dot" /> : null} /></section><section className="panel calendar-agenda"><p className="eyebrow">{date.toLocaleDateString('en-US', { month: 'long', day: 'numeric' }).toUpperCase()}</p><h3>Due this day</h3>{dayTasks.length ? dayTasks.map((task) => <div className="agenda-item" key={task._id}><span className={`agenda-status ${task.isCompleted ? 'done' : ''}`}>{task.isCompleted && <Check size={12} />}</span><div><strong>{task.title}</strong><small>{task.subject} · {task.priority} priority</small></div></div>) : <EmptyState compact text="Nothing due on this day." />}</section></div></div>; }
function TrackedTimer({ onSession }) { const [seconds, setSeconds] = useState(25 * 60); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return undefined; const id = setInterval(() => setSeconds((value) => value > 0 ? value - 1 : 0), 1000); return () => clearInterval(id); }, [running]); useEffect(() => { if (seconds === 0 && running) { setRunning(false); api.post('/study-sessions', { durationMinutes: 25 }).then(() => { toast.success('Focus session saved'); onSession(); }).catch(() => toast.error('Could not save session')); } }, [seconds, running]); const mins = String(Math.floor(seconds / 60)).padStart(2, '0'); const secs = String(seconds % 60).padStart(2, '0'); return <div className="timer-page"><div><p className="eyebrow">DEEP WORK MODE</p><h1>Protect your focus.</h1><p className="muted">A 25-minute sprint, then a well-earned breath.</p></div><div className="timer-card"><div className="timer-orbit"><span>{mins}:{secs}</span><small>FOCUS SESSION</small></div><div className="timer-controls"><button className="secondary-button" onClick={() => { setRunning(false); setSeconds(25 * 60); }}><TimerReset size={17} /> Reset</button><button className="primary-button" onClick={() => setRunning(!running)}>{running ? 'Pause session' : 'Start session'} <ChevronRight size={17} /></button></div><div className="session-note"><Sparkles size={16} /> Finished sessions are saved to your weekly study time</div></div></div>; }

function Overview({ tasks, completed, percent, quote, onNewQuote, onAdd, onNavigate }) { const chartData = subjects.slice(1).map((name) => ({ name: name.slice(0, 5), count: tasks.filter((task) => task.subject === name).length })).filter((item) => item.count); const next = tasks.find((task) => !task.isCompleted); return <><div className="welcome-row"><div><p className="eyebrow">YOUR OVERVIEW</p><h1>A little structure goes a long way.</h1><p className="muted">Here’s your study rhythm at a glance.</p></div><button className="primary-button" onClick={onAdd}><Plus size={18} /> Add task</button></div><div className="stat-grid"><Stat icon={<ListTodo />} label="Total tasks" value={tasks.length} accent="peach" /><Stat icon={<Check />} label="Completed" value={completed} accent="teal" /><Stat icon={<ListTodo />} label="Remaining" value={tasks.length - completed} accent="violet" /><Stat icon={<Clock3 />} label="Focus sessions" value="12" accent="gold" /></div><div className="progress-panel"><div><div className="panel-label"><span>Weekly momentum</span><strong>{percent}% complete</strong></div><div className="progress-track"><div style={{ width: `${percent}%` }} /></div><p className="muted small">{completed ? 'You are building a strong habit. Keep the rhythm going.' : 'Complete your first task to start your momentum.'}</p></div><div className="progress-ring"><strong>{percent}%</strong><span>done</span></div></div><div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">DISTRIBUTION</p><h3>Tasks by subject</h3></div><button className="text-button" onClick={() => onNavigate('tasks')}>View tasks <ChevronRight size={15} /></button></div>{chartData.length ? <ResponsiveContainer width="100%" height={210}><BarChart data={chartData} barSize={24}><CartesianGrid vertical={false} stroke="#e7e4df" /><XAxis dataKey="name" axisLine={false} tickLine={false} fontSize={11} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} fontSize={11} /><Tooltip cursor={{ fill: '#faf7f2' }} /><Bar dataKey="count" radius={[6, 6, 0, 0]} fill="#2b7a78" /></BarChart></ResponsiveContainer> : <EmptyState compact text="Add tasks to see your study mix." />}</section><section className="panel next-panel"><div className="panel-heading"><div><p className="eyebrow">UP NEXT</p><h3>Keep your focus</h3></div><TimerReset size={20} color="#ef8354" /></div>{next ? <div className="next-task"><div className="task-check" onClick={() => onNavigate('tasks')}><CircleUserRound size={18} /></div><div><strong>{next.title}</strong><span>{next.subject} <b className={`priority ${next.priority.toLowerCase()}`}>{next.priority}</b></span></div></div> : <EmptyState compact text="Everything is complete. Enjoy the win." />}<div className="quote"><Quote size={18} /><p>{quote}</p><button className="text-button quote-refresh" onClick={onNewQuote}>New quote</button></div></section></div></>;
}
function QuickTiles({ tiles, onNavigate }) { return <section className="quick-tiles"><div className="quick-heading"><p className="eyebrow">EXPLORE YOUR TOOLS</p><h3>Everything in one place</h3></div><div className="quick-grid">{tiles.map(({ id, label, icon: Icon, tint, value, note }) => <button key={id} style={{ '--tint': tint }} onClick={() => onNavigate(id)}><span className="quick-icon"><Icon size={20} /></span><strong>{value}</strong><small>{note}</small><b>{label} <ChevronRight size={14} /></b></button>)}</div></section>; }
function Stat({ icon, label, value, accent }) { return <div className={`stat-card ${accent}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>; }

function TasksView({ tasks, subject, setSubject, onAdd, onToggle, onEdit, onDelete }) { const active = tasks.filter((task) => !task.isCompleted); const completed = tasks.filter((task) => task.isCompleted); const group = (title, items) => <section className="task-group"><div className="task-group-heading"><h3>{title}</h3><span>{items.length}</span></div>{items.length ? items.map((task) => <TaskRow key={task._id} task={task} onToggle={onToggle} onEdit={onEdit} onDelete={onDelete} />) : <EmptyState compact text={title === 'Active tasks' ? 'You are all caught up.' : 'Completed tasks will appear here.'} />}</section>; return <><div className="page-title-row"><div><p className="eyebrow">TASK BOARD</p><h1>Make it manageable.</h1><p className="muted">One clear next step at a time.</p></div><button className="primary-button" onClick={onAdd}><Plus size={18} /> Add task</button></div><div className="filter-bar"><div className="subject-tabs">{subjects.map((item) => <button className={subject === item ? 'selected' : ''} key={item} onClick={() => setSubject(item)}>{item}</button>)}</div><div className="search-chip"><Search size={16} /> {tasks.length} {tasks.length === 1 ? 'task' : 'tasks'}</div></div>{group('Active tasks', active)}{group('Completed tasks', completed)}</>; }
function TaskRow({ task, onToggle, onEdit, onDelete }) { const due = task.dueDate ? new Date(task.dueDate) : null; const overdue = due && !task.isCompleted && due < new Date(); return <div className={`task-row ${task.isCompleted ? 'completed' : ''}`}><button className={`task-check ${task.isCompleted ? 'done' : ''}`} onClick={() => onToggle(task)}>{task.isCompleted && <Check size={15} />}</button><div className="task-info"><strong>{task.title}</strong><div><span className="subject-dot" />{task.subject}<b className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</b>{due && <span className={`due-date ${overdue ? 'overdue' : ''}`}><CalendarDays size={13} />{overdue ? 'Overdue' : due.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>}</div></div><div className="task-actions"><button className="icon-button" onClick={() => onEdit(task)} title="Edit task"><Pencil size={16} /></button><button className="icon-button danger" onClick={() => onDelete(task)} title="Delete task"><Trash2 size={16} /></button></div></div>; }

function TaskModal({ initial, onClose, onSave }) { const [form, setForm] = useState({ ...blankTask, ...initial, dueDate: initial.dueDate ? new Date(initial.dueDate).toISOString().slice(0, 10) : '' }); return <div className="modal-backdrop"><form className="modal" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><div className="modal-heading"><div><p className="eyebrow">TASK DETAILS</p><h2>{initial._id ? 'Edit task' : 'New task'}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={20} /></button></div><label>Task title<input required autoFocus value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="What do you want to accomplish?" /></label><div className="form-grid"><label>Subject<select value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })}>{subjects.slice(1).map((item) => <option key={item}>{item}</option>)}</select></label><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select></label></div><label>Due date<input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button"><Save size={17} /> Save task</button></div></form></div>; }
export default App;
